REMOVE="
/product/priv-app/GmsCore
/product/priv-app/GoogleOneTimeInitializer
/product/priv-app/GooglePartnerSetup
/product/priv-app/GoogleRestore
/product/priv-app/Phonesky
/product/priv-app/FamilyLinkParentalControls
/product/priv-app/Messages
/product/priv-app/SearchSelector
/product/priv-app/Turbo
/product/priv-app/Velvet
/product/priv-app/HotwordEnrollmentOKGoogleEx4TL3210
/product/priv-app/HotwordEnrollmentXGoogleEx4TL3210
/product/app/Chrome
/product/app/DuoStub
/product/app/Gmail2
/product/app/GoogleCalendarSyncAdapter
/product/app/GoogleLocationHistory
/product/app/Maps
/product/app/SpeechServicesByGoogle
/product/app/WebviewGoogle
/product/app/YouTube
/system/system_ext/priv-app/GoogleFeedback
/system/system_ext/priv-app/GoogleServicesFramework
/system/system_ext/priv-app/SetupWizard
/apex/com.android.adservices/priv-app/AdServicesApkGoogle@341316030
/system/priv-app/AREmoji
/system/app/ARDrawing
/system/priv-app/AvatarEmojiSticker
/system/app/ARCore
/data/app/~~DRaNTCFDFgqk6kUtP8eeAQ==/com.samsung.android.samsungpassautofill-y3eddy7eb1VXvN1CwEvPOQ==
/data/app/~~jKK4WTq8R7QhKNM7sjKIRg==/com.samsung.android.visionintelligence-YQf7nAEHZxqRjsJsaLmeHg==
/system/priv-app/Bixby
/data/app/~~_P3aopgO0QZuGH-q0-yZTg==/com.samsung.android.bixbyvision.framework-DGvwHV1pRiXcKrHPSmb_Tw==
/system/app/MdecService
/system/priv-app/HWResourceShare
/system/priv-app/StickerFaceARAvatar
/system/priv-app/RubinVersion34
/system/app/DailyBoard
/system/app/DAAgent
/system/app/VideoTrimmer
/data/app/~~Q0m1XQqXTx5xU5L73Q8uvA==/com.samsung.android.aremojieditor-53uiofCMiVEtxWqv0y8gpw==
/system/app/Foundation
/system/priv-app/GameTools_Dream
/system/priv-app/GameOptimizingService
/system/priv-app/GpuWatchApp
/system/app/LiveDrawing
/system/app/LiveTranscribe
/system/app/ParentalCare
/system/app/KidsHome_Installer
/system/app/HiyaService
/system/app/SmartSwitchAgent
/system/app/SmartSwitchStub
/system/app/StickerCenter
/data/app/~~6WEncYQRL6zvyR1PcvSZ9Q==/com.samsung.android.inputshare-emnuN1YdU87M259Bh6e9Og==
/system/priv-app/OneDrive_Samsung_v3
/data/app/~~UZHgk2XoJ6ekWp-V6ATmPQ==/com.osp.app.signin-Ybs4yC11aNhH0Fc2RXhTqg==
/data/app/~~F9rUtmGmY2d_2wwTWHBPhQ==/com.samsung.android.bixby.ondevice.eses-92aUB06KXoHBb1gCzWiISA==
/system/app/Fast
/system/app/VideoEditorLite_Dream_N
/system/app/VTCameraSetting
"
