REMOVE="
/product/priv-app/GmsCore
/product/priv-app/GoogleOneTimeInitializer
/product/priv-app/GooglePartnerSetup
/product/priv-app/GoogleRestore
/product/priv-app/Phonesky
/product/priv-app/FamilyLinkParentalControls
/product/priv-app/Messages
/product/priv-app/SearchSelector
/product/priv-app/Turbo
/product/priv-app/Velvet
/product/priv-app/HotwordEnrollmentOKGoogleEx4TL3210
/product/priv-app/HotwordEnrollmentXGoogleEx4TL3210
/product/app/Chrome
/product/app/DuoStub
/product/app/Gmail2
/product/app/GoogleCalendarSyncAdapter
/product/app/GoogleLocationHistory
/product/app/Maps
/product/app/SpeechServicesByGoogle
/product/app/WebviewGoogle
/product/app/YouTube
/system/system_ext/priv-app/GoogleFeedback
/system/system_ext/priv-app/GoogleServicesFramework
/system/system_ext/priv-app/SetupWizard
/apex/com.android.adservices/priv-app/AdServicesApkGoogle@341316030
/system/priv-app/AREmoji
/system/app/ARDrawing
/system/priv-app/AvatarEmojiSticker
/system/app/ARCore
/system/priv-app/Bixby
/system/app/MdecService
/system/priv-app/HWResourceShare
/system/priv-app/StickerFaceARAvatar
/system/priv-app/RubinVersion34
/system/app/DailyBoard
/system/app/DAAgent
/system/app/VideoTrimmer
/system/app/Foundation
/system/priv-app/GameTools_Dream
/system/priv-app/GameOptimizingService
/system/priv-app/GpuWatchApp
/system/app/LiveDrawing
/system/app/LiveTranscribe
/system/app/ParentalCare
/system/app/KidsHome_Installer
/system/app/HiyaService
/system/app/SmartSwitchAgent
/system/app/SmartSwitchStub
/system/app/StickerCenter
/system/priv-app/OneDrive_Samsung_v3
/system/priv-app/SamsungAccount/system/app/Fast
/system/app/VideoEditorLite_Dream_N
/system/app/VTCameraSetting
/system/priv-app/SamsungBilling
/system/priv-app/SamsungCalendarProvider
/system/priv-app/SamsungSmartSuggestions
/system/priv-app/SecMyFiles2020
/system/priv-app/YourPhone_P1_5
/system/priv-app/SmartSwitchAssistant
/system/priv-app/SKMSAgent
/system/priv-app/SamsungPass
/system/priv-app/SamsungMessages
/system/priv-app/SamsungContacts
/system/priv-app/SamsungDialer
/system/priv-app/Routines
/system/priv-app/LinkToWindowsService
/system/priv-app/KnoxPushManager
/system/priv-app/AuthFramework
/system/priv-app/AREmojiEditor
/system/priv-app/AutoDoodle
/system/priv-app/BixbyVisionFramework3.5
/system/app/BixbyWakeup
"
