REMOVE="
/product/priv-app/GmsCore
/product/priv-app/GoogleOneTimeInitializer
/product/priv-app/GooglePartnerSetup
/product/priv-app/GoogleRestore
/product/priv-app/Phonesky
/product/priv-app/FamilyLinkParentalControls
/product/priv-app/Messages
/product/priv-app/SearchSelector
/product/priv-app/Turbo
/product/priv-app/Velvet
/product/priv-app/HotwordEnrollmentOKGoogleEx4TL3210
/product/priv-app/HotwordEnrollmentXGoogleEx4TL3210
/product/app/Chrome
/product/app/DuoStub
/product/app/Gmail2
/product/app/GoogleCalendarSyncAdapter
/product/app/GoogleLocationHistory
/product/app/Maps
/product/app/SpeechServicesByGoogle
/product/app/WebviewGoogle
/product/app/YouTube
/system/system_ext/priv-app/GoogleFeedback
/system/system_ext/system/priv-app/GoogleServicesFramework
/system/system_ext/system/priv-app/SetupWizard
/apex/com.android.adservices/priv-app/AdServicesApkGoogle@341316030
/system/priv-app/AREmoji
/system/app/ARDrawing
/system/priv-app/AvatarEmojiSticker
/system/app/ARCore
/data/app/~~DRaNTCFDFgqk6kUtP8eeAQ==/com.samsung.android.samsungpassautofill-y3eddy7eb1VXvN1CwEvPOQ==
/data/app/~~jKK4WTq8R7QhKNM7sjKIRg==/com.samsung.android.visionintelligence-YQf7nAEHZxqRjsJsaLmeHg==
/system/priv-app/Bixby
/data/app/~~_P3aopgO0QZuGH-q0-yZTg==/com.samsung.android.bixbyvision.framework-DGvwHV1pRiXcKrHPSmb_Tw==
/system/app/MdecService
/system/priv-app/HWResourceShare
/system/priv-app/StickerFaceARAvatar
/system/priv-app/RubinVersion34
/system/app/DailyBoard
/system/app/DAAgent
/system/app/VideoTrimmer
"
